libname data "\\Mac\Home\Documents\CONNECT_projects\Biospecimen_Feb2022\Jing_projects\biospecQC_03082022\data";
option nofmterr;
data recr_veri_bio;set data.prod_recrbio_merged_07252022;run;
data concept_idsbios; set data.prod_biospecimen_07252022;run;
data recru_biospec_prod;
set recr_veri_bio; 
if connect_id >0 then do;
if BioSpm_Visit_v1r0=266600170 and RcrtV_Verification_v1r0 =197316935 then output;end;
run;/*n=133 baseline*/

ods html close;
options ls=140;
proc freq data=Concept_IDsBios; table BioSpm_Location_v1r0*RcrtES_Site_v1r0/list missing ;run;
***                                                                                                                Cumulative    Cumulative
                            BioSpm_Location_v1r0                   RcrtES_Site_v1r0    Frequency     Percent     Frequency      Percent
             ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
             SF Cancer Center LL                    Sanford Health                            9        6.77             9         6.77
             Marshfield                             Marshfield Clinic Health System          22       16.54            31        23.31
             Lake Hallie                            Marshfield Clinic Health System           8        6.02            39        29.32
             UC-DCAM                                University of Chicago Medicine           19       14.29            58        43.61
             HP Research Clinic                     HealthPartners                           56       42.11           114        85.71
             HFH Cancer Pavilion Research Clinic    Henry Ford Health System                 19       14.29           133       100.00
********;
proc sql;
create table biosbase_tube as
   select Connect_id,RcrtES_Site_v1r0,BioSpm_ColIDScan_v1r0,BioSpm_ColIDEntered_v1r0,BioSpm_Setting_v1r0,BioSpm_Visit_v1r0,
BioCol_ColTime_v1r0,SrvBLM_ResSrvCompl_v1r0, SrvBLM_TmStart_v1r0, SrvBLM_TmComplete_v1r0,BL_BioChk_Time_v1r0,
BL_BioFin_CheckOutTime_v1r0,BioRec_CollectFinalTime_v1r0,BioSpm_Location_v1r0,
	max(SSTube1_BioCol_TubeColl) as SSTube1_TubeColl_yes,
	max(SSTube2_BioCol_TubeCollected) as SSTube2_TubeColl_yes ,
	max(EDTATube1_BioCol_TubeCollected) as EDTATube1_TubeColl_yes ,
	max(HepTube1_BioCol_TubeCollected) as HepTube1_TubeColl_yes ,
	max(ACDTube1_BioCol_TubeCollected) as  ACDTube1_TubeColl_yes,
	max(UrineTube1_BioCol_TubeCollected) as UrineTube1_TubeCollected_yes,
	max(MWTube1_BioCol_TubeCollected) as MWTube1_TubeCollected_yes ,
	max(BiohazBlU_BioCol_TubeColl) as BiohazBlU_TubeColl_yes 
   from recru_biospec_prod /*baseline*/
      group by Connect_id
      order by Connect_id;
quit;
run;/*n=133*/



***for all the possible deviations in the biospecimen
****update the shipping time
Name From: BioRec_ShipFlag_v1r0 To: BioRec_CollectFinal_v1r0

CID 556788178
Question Text From: Autogenerated date/time when go to shipping
Question Text To: Autogenerated date/time when collection entry finalized
Label From: Date/Time go to shipping To: Date/Time Collection Entry Finalized
Name From: BioRec_ShipTime_v1r0 To: BioRec_CollectFinalTime_v1r0
****************
Jun.23, as Dominique asked:
the time gap between biospecimen collection time (BioCol_ColTime_v1r0) with survey complete time (SrvBLM_TmComplete_v1r0) by 
day to check participants with biospecimen collection in each site in this table, right?
 
For the average of the visit length as you described ? metric of the visit length (check-out time minus check-in time) in 
minutes, along with a version of this that excludes outliers in case they forget to check someone out until the next day 
it will throw off the average·
 
I need exclude the outliers as you defined: Outliers: anyone who wasn? promptly checked out after biospecimen collection till 
the next day,
The averaged visit length would be the difference (min) among the non-outlier group: 
BL_BioFin_CheckOutTime_v1r0 - BL_BioChk_Time_v1r0/ (total N- n of outliers);
********************;

proc format;
	VALUE BioColTubeCompleFmt
			104430631 = "No"
			353358909 = "Complete"
			200000000 = "Partial";
	VALUE BioSpecimenFmt
			104430631 = "No Blood, or Urine or MouthWash Collection"
			353358909 = "Any Collections of Blood, or Urine or MouthWash"; 
proc sort data=biosbase_tube; by connect_id; run;
data biotube_col;
set biosbase_tube;
by connect_id;
if mean(SSTube1_TubeColl_yes,SSTube2_TubeColl_yes,EDTATube1_TubeColl_yes,HepTube1_TubeColl_yes,ACDTube1_TubeColl_yes)= 353358909 then BioBld_Complete=353358909;
else if mean(SSTube1_TubeColl_yes,SSTube2_TubeColl_yes,EDTATube1_TubeColl_yes,HepTube1_TubeColl_yes,ACDTube1_TubeColl_yes)=104430631 then BioBld_Complete=104430631;
else if 353358909 > mean(SSTube1_TubeColl_yes,SSTube2_TubeColl_yes,EDTATube1_TubeColl_yes,HepTube1_TubeColl_yes,ACDTube1_TubeColl_yes)> 104430631 then BioBld_Complete=200000000;

if last.connect_id=1 then output;
format BioBld_Complete BioColTubeCompleFmt.
SSTube1_TubeColl_yes BioColTubeCollFmt. SSTube2_TubeColl_yes BioColTubeCollFmt. EDTATube1_TubeColl_yes BioColTubeCollFmt. HepTube1_TubeColl_yes BioColTubeCollFmt.
ACDTube1_TubeColl_yes BioColTubeCollFmt. UrineTube1_TubeCollected_yes BioColTubeCollFmt. MWTube1_TubeCollected_yes BioColTubeCollFmt. BiohazBlU_TubeColl_yes BioColTubeCollFmt.;

keep connect_id RcrtES_Site_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 BioCol_ColTime_v1r0 BioRec_CollectFinalTime_v1r0 SSTube1_TubeColl_yes SSTube2_TubeColl_yes EDTATube1_TubeColl_yes 
HepTube1_TubeColl_yes ACDTube1_TubeColl_yes UrineTube1_TubeCollected_yes MWTube1_TubeCollected_yes  BiohazBlU_TubeColl_yes biobld_complete BioSpm_Location_v1r0
SrvBLM_ResSrvCompl_v1r0 SrvBLM_TmStart_v1r0 SrvBLM_TmComplete_v1r0 BL_BioChk_Time_v1r0 BL_BioFin_CheckOutTime_v1r0;
run;
proc format;
value checkdayfmt
0="within 24 hours"
1="more than 24 hrs less than 48 hrs"
2="more than 2 days"
3="more than 3 days";

data biotube_col1;set biotube_col;
tm_biocolSuv=intck("hour", BioCol_ColTime_v1r0,SrvBLM_TmComplete_v1r0);
time_biochk=intck("minute", BL_BioChk_Time_v1r0,BL_BioFin_CheckOutTime_v1r0);
if abs(time_biochk/60) > 24 then biochk_outlier=1;
else if 0< =abs(time_biochk/60) < = 24 then biochk_outlier=0;

if 0<= abs(tm_biocolSuv) < =24 then checkvisit=0;
else if 48 =>abs(tm_biocolsuv)>24 then checkvisit=1;
else if  72 =>abs(tm_biocolsuv)>48 then checkvisit=2;
else if  abs(tm_biocolSuv)>72 then checkvisit=3;

label tm_biocolSuv="time (hour) between biospecimen collection time with survey completion time" 
time_biochk="visit time by minutes (check-out time minus check-in time)";
attrib checkvisit format=checkdayfmt. label= "Survey Completion Time";
run;

ods html;
/*proc print data=biotube_col noobs label;
var connect_id BioCol_ColTime_v1r0 BioRec_CollectFinalTime_v1r0 SrvBLM_TmComplete_v1r0;
run;*/
proc sort data=recr_veri_bio nodupkey out=recrbio dupout=dup;by connect_id;run;/*nodup*/

proc sql;
create table recru_biotube_prod as 
select
a. *, b. BioBld_Complete, b. UrineTube1_TubeCollected_yes, b. MWTube1_TubeCollected_yes, b. time_biochk, 
b. tm_biocolSuv, b. checkvisit 
/*b. BioSpm_Visit_v1r0, b. BioSpm_Setting_v1r0, b. BioSpm_Location_v1r0,*/
from 
merged_recrbio_prod a /*1134*/
full join
biotube_col1 b /*n=73*/
on a. Connect_ID = b. Connect_ID
order by b. Connect_ID;
quit;
run;/*1385, 133 with biospecimen*/

proc freq data=recru_biotube_prod; 
table BL_BioChk_Complete_v1r0 RcrtES_Site_v1r0 BioSpm_Setting_v1r0 SrvBLM_ResSrvCompl_v1r0
SrvBLM_ResSrvCompl_v1r0*BL_BioChk_Complete_v1r0/list missing; run;
***                                             BL_BioChk_                             Cumulative    Cumulative
                                          Complete_v1r0    Frequency     Percent     Frequency      Percent
                                          ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                      .        1251       90.32          1251        90.32
                                                    No          133        9.60          1384        99.93
                                                    Yes           1        0.07          1385       100.00


                                                                         Site

                                                                                             Cumulative    Cumulative
                                                RcrtES_Site_v1r0    Frequency     Percent     Frequency      Percent
                                 ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                 Kaiser Permanente Colorado              262       18.92           262        18.92
                                 Kaiser Permanente Hawaii                 75        5.42           337        24.33
                                 Marshfield Clinic Health System         122        8.81           459        33.14
                                 Kaiser Permanente Georgia               105        7.58           564        40.72
                                 Kaiser Permanente Northwest             307       22.17           871        62.89
                                 HealthPartners                          330       23.83          1201        86.71
                                 Henry Ford Health System                 45        3.25          1246        89.96
                                 Sanford Health                          104        7.51          1350        97.47
                                 University of Chicago Medicine           35        2.53          1385       100.00


                                                                  Collection Setting

                                               BioSpm_                             Cumulative    Cumulative
                                          Setting_v1r0    Frequency     Percent     Frequency      Percent
                                          ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                     .        1252       90.40          1252        90.40
                                              Research         133        9.60          1385       100.00


                                                Blood/urine/mouthwash combined research survey-Complete

                                            SrvBLM_Res
                                             SrvCompl_                             Cumulative    Cumulative
                                                  v1r0    Frequency     Percent     Frequency      Percent
                                           ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                           Submitted           127        9.17           127         9.17
                                           Started               2        0.14           129         9.31
                                           Not Started        1256       90.69          1385       100.00

                                SrvBLM_ResSrv          BL_BioChk_                             Cumulative    Cumulative
                                    Compl_v1r0       Complete_v1r0    Frequency     Percent     Frequency      Percent
                              ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                              Submitted           No                       127        9.17           127         9.17
                              Started             No                         1        0.07           128         9.24
                              Started             Yes                        1        0.07           129         9.31
                              Not Started           .                     1251       90.32          1380        99.64
                              Not Started         No                         5        0.36          1385       100.00
***********;
proc freq data=biotube_col1;
table MWTube1_TubeCollected_yes  BiohazBlU_TubeColl_yes biobld_complete/list missing; 
format BioBld_Complete BioColTubeCompleFmt.;
run;
 *****                                             MWTube1_
                                                 Tube
                                           Collected_                             Cumulative    Cumulative
                                                  yes    Frequency     Percent     Frequency      Percent
                                           ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                  No            1        0.75             1         0.75
                                                  Yes         132       99.25           133       100.00


                                              Biohaz
                                                BlU_
                                                Tube                             Cumulative    Cumulative
                                            Coll_yes    Frequency     Percent     Frequency      Percent
                                            ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                 No            1        0.75             1         0.75
                                                 Yes         132       99.25           133       100.00


                                               BioBld_                             Cumulative    Cumulative
                                              Complete    Frequency     Percent     Frequency      Percent
                                          ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                              No                 5        3.76             5         3.76
                                              Partial            4        3.01             9         6.77
                                              Complete         124       93.23           133       100.00
*******;

data bio_settingfmt; 
attrib BioSpm_Setting_v1r0 label = "Collection Setting" format = BioSpmSettingFmt.;
input BioSpm_Setting_v1r0 @@;
cards;
534621077 664882224 103209024
run;
data bio_settingfmt;
length Label $20.;
set bio_settingfmt;
if BioSpm_Setting_v1r0=534621077 then Label="   Research";
if BioSpm_Setting_v1r0=664882224 then Label="   Clinical";
if BioSpm_Setting_v1r0=103209024 then Label="   Home"; run;


data tmp; ;set recru_biotube_prod;
if biobld_complete = . then biobld_complete =104430631;
if UrineTube1_TubeCollected_yes=. then UrineTube1_TubeCollected_yes=104430631;
if MWTube1_TubeCollected_yes=. then MWTube1_TubeCollected_yes=104430631;
if BioFin_BaseBloodCol_v1r0=. then BioFin_BaseBloodCol_v1r0=104430631;
if BioFin_BaseUrineCol_v1r0=. then BioFin_BaseUrineCol_v1r0=104430631;
if BioFin_BaseMouthCol_v1r0=. then BioFin_BaseMouthCol_v1r0=104430631;
if  BioFin_BaseBloodCol_v1r0=BioFin_baseUrineCol_v1r0=BioFin_BaseMouthCol_v1r0=104430631 then BioFin_BaseSpeci_v1r0=104430631;
else BioFin_BaseSpeci_v1r0=353358909;

format biobld_complete BioColTubeCompleFmt. UrineTube1_TubeCollected_yes BioColTubeCollFmt. MWTube1_TubeCollected_yes BioColTubeCollFmt.
BioFin_BaseBloodCol_v1r0 BioColTubeCollFmt. BioFin_BaseUrineCol_v1r0 BioColTubeCollFmt. BioFin_BaseMouthCol_v1r0 BioColTubeCollFmt.
BioFin_BaseSpeci_v1r0 BioSpecimenFmt.;
if BioSpm_Setting_v1r0=664882224 then delete;
if BioSpm_Visit_v1r0=. then BioSpm_Visit_v1r0=266600170;
if connect_id=9122429867 then delete;/*no this connect id in the prod*/
run;/*to remove this connect id from recrutment data*/ /*n=1385*/

proc freq data=tmp; table RcrtES_Site_v1r0 BioSpm_Setting_v1r0 BioFin_BaseSpeci_v1r0/list missing; run; 
***                                                                                            Cumulative    Cumulative
                                                RcrtES_Site_v1r0    Frequency     Percent     Frequency      Percent
                                 ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                 Kaiser Permanente Colorado              262       18.92           262        18.92
                                 Kaiser Permanente Hawaii                 75        5.42           337        24.33
                                 Marshfield Clinic Health System         122        8.81           459        33.14
                                 Kaiser Permanente Georgia               105        7.58           564        40.72
                                 Kaiser Permanente Northwest             307       22.17           871        62.89
                                 HealthPartners                          330       23.83          1201        86.71
                                 Henry Ford Health System                 45        3.25          1246        89.96
                                 Sanford Health                          104        7.51          1350        97.47
                                 University of Chicago Medicine           35        2.53          1385       100.00


                                                                  Collection Setting

                                               BioSpm_                             Cumulative    Cumulative
                                          Setting_v1r0    Frequency     Percent     Frequency      Percent
                                          ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                     .        1252       90.40          1252        90.40
                                              Research         133        9.60          1385       100.00


                                                                                                     Cumulative    Cumulative
                                                   BioFin_BaseSpeci_v1r0    Frequency     Percent     Frequency      Percent
                         ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                         No Blood, or Urine or MouthWash Collection             1253       90.47          1253        90.47
                         Any Collections of Blood, or Urine or MouthWash         132        9.53          1385       100.00
******;
proc freq data=tmp;
title "Percent (and number) of verified participants Blood, Urine and Mouthwash collected with the baseline participants 08082022";
tables BioFin_baseUrineCol_v1r0*BioFin_BaseMouthCol_v1r0*BioFin_BaseBloodCol_v1r0 BioFin_BaseBloodCol_v1r0/list missing out=one;
run;/*one is the blood collection*/
**                         BioFin_Base         BioFin_Base         BioFin_Base                             Cumulative    Cumulative
                       UrineCol_v1r0       MouthCol_v1r0       BloodCol_v1r0    Frequency     Percent     Frequency      Percent
                    ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                    No                  No                  No                      1253       90.47          1253        90.47
                    No                  Yes                 Yes                        2        0.14          1255        90.61
                    Yes                 Yes                 No                         4        0.29          1259        90.90
                    Yes                 Yes                 Yes                      126        9.10          1385       100.00


                                                           Baseline blood sample collected

                                             BioFin_
                                                Base
                                               Blood                             Cumulative    Cumulative
                                            Col_v1r0    Frequency     Percent     Frequency      Percent
                                            ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                 No         1257       90.76          1257        90.76
                                                 Yes         128        9.24          1385       100.00
***;
proc transpose data = one out=t_one prefix=BioFin_BaseBloodCol_v1r0;
id BioFin_BaseBloodCol_v1r0;
run;

filename tab1ctsp '\\Mac\Home\Documents\My SAS Files\9.4\SASmacro\Table1_CTSPedia_local.sas';
%include tab1ctsp ;

filename tab1prt '\\Mac\Home\Documents\My SAS Files\9.4\SASmacro\Table1Print_CTSPedia.sas';
%include tab1prt;

data tmp2;set recru_biotube_prod;
if BioFin_BaseBloodCol_v1r0=. then BioFin_BaseBloodCol_v1r0=104430631;
if BioFin_BaseUrineCol_v1r0=. then BioFin_BaseUrineCol_v1r0=104430631;
if BioFin_BaseMouthCol_v1r0=. then BioFin_BaseMouthCol_v1r0=104430631;
if UrineTube1_TubeCollected_yes=. then UrineTube1_TubeCollected_yes=104430631;
if MWTube1_TubeCollected_yes=. then MWTube1_TubeCollected_yes=104430631;
if Biobld_complete=. then Biobld_complete=104430631;
format BioBld_Complete  BioColTubeCompleFmt. BioFin_BaseBloodCol_v1r0 BioColTubeCollFmt. 
BioFin_BaseUrineCol_v1r0 BioColTubeCollFmt. BioFin_BaseMouthCol_v1r0 BioColTubeCollFmt.
 MWTube1_TubeCollected_yes BioColTubeCollFmt. MWTube1_TubeCollected_yes BioColTubeCollFmt.;
where connect_id>0;
run;
/*Survery baseline biospecimen*/
data tmp3;set tmp2;
if BioSpm_Setting_v1r0= 534621077 then do;
if BioFin_BaseBloodCol_v1r0= 104430631 a BioFin_BaseUrineCol_v1r0=353358909 or  BioFin_BaseMouthCol_v1r0=353358909 then output;
end;
run;/*n=132*/
ods html;
proc print data=tmp2 noobs;
where BioSpm_Setting_v1r0=534621077 and BioFin_BaseBloodCol_v1r0= 104430631 and BioFin_BaseUrineCol_v1r0=104430631 and  BioFin_BaseMouthCol_v1r0=104430631;
var RcrtV_Verification_v1r0 RcrtSI_RecruitType_v1r0 connect_ID BL_BioChk_Complete_v1r0 RcrtES_Site_v1r0 BioSpm_Setting_v1r0 SrvBLM_ResSrvCompl_v1r0
BioSpm_ColIDScan_v1r0 BioFin_BaseBloodCol_v1r0 BioFin_BaseUrineCol_v1r0 BioFin_BaseMouthCol_v1r0;
run;
data bldcompl;set tmp;
if connect_id=connectbio_id and BioFin_BaseBloodCol_v1r0=353358909 then output;
run;/*Table 10. n=128*/
%Table1_CTSPedia(DSName=bldcompl, GroupVar=Biobld_complete,
                  NumVars=,
FreqVars = BioFin_BaseBloodCol_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, FreqCell=N(RP), Print=Y,Label=L,Out=Biocmp_blood);

%macro freq_t(var, note, date,condition, format,t);
proc freq data=tmp;
title "Percent (and number) of verified participants with the baseline &note collected from participants of all sites &date";
tables &var /list missing out=&t. noprint;
format &var &format;
where connect_id &condition;
run;

proc transpose data=&t out=t_&t. prefix=&var._;
format &var &format;
id &var.;
idlabal &var.;
run;

data tmp_c; set tmp; 
where connect_id &condition;run;

%Table1_CTSPedia(DSName=tmp_c, GroupVar=&var,
                NumVars=,
FreqVars = RcrtES_Site_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, FreqCell=N(RP), Print=Y,Label=L,Out=Biospec_&t.);

%mend;
%freq_t(BioFin_BaseSpeci_v1r0, any biospecimen, 08082022, >0,BioSpecimenFmt.,zero);/*the table is freqcell=N(CP)*/
%freq_t(BioFin_BaseBloodCol_v1r0 , blood, 08082022, >0, BioColTubeCollFmt.,one);/*the table is freqcell=N(RP)*/
%freq_t(BioFin_baseUrineCol_v1r0, Urine, 08082022, >0,BioColTubeCollFmt., two);/*the table is freqcell=N(RP)*/
%freq_t(BioFin_BaseMouthCol_v1r0, Mouthwash, 08082022, >0,BioColTubeCollFmt.,three);/*the table is freqcell=N(RP)*/

/*%freq_t(BioFin_BaseBloodCol_v1r0 , blood of all biospecimen collection, 04042022, =connectbio_id,BioColTubeCollFmt.,four);
%freq_t(BioFin_baseUrineCol_v1r0, Urine of all biospecimen collection, 04042022, =connectbio_id,BioColTubeCollFmt.,five);
%freq_t(BioFin_BaseMouthCol_v1r0, Mouthwash of all biospecimen collection, 04042022, =connectbio_id,BioColTubeCollFmt.,six);*/

%freq_t(BioBld_Complete, complete blood collection of all biospecimen collection, 08082022, =connectbio_id and BioFin_BaseBloodCol_v1r0=353358909,BioColTubeCollFmt.,seven);

data zero;
set zero;
total=count*100/percent; 
N_percent=put(count, 4.2)||" ("||put(percent,4.2)||")";
run;
proc transpose data=zero out=t_zero prefix=_;
format BioFin_BaseSpeci_v1r0 BioSpecimenFmt.;
var N_percent;
id BioFin_BaseSpeci_v1r0;
idlabel BioFin_BaseSpeci_v1r0;
run;
/*here the total numbero of biospecimen should be manually input due to the difference in each biospecimen data by week***/
data t_zero;
set t_zero;
total="1385 (100)";
label total="total verified participants";
run;


%macro coll_check(type);
data biospec; set tmp2; where connect_id=connectbio_id ; run;

%Table1_CTSPedia(DSName=biospec, GroupVar=BioFin_Base&type.Col_v1r0,
                NumVars=,
FreqVars = BioSpm_Setting_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, FreqCell=N(RP), Print=Y,Label=L,Out=&type);

proc sort data=bio_settingfmt; by label;run;
proc sort data=&type; by label; run;
data combo; merge bio_settingfmt  &type.;
by label;
run;
data &type.1; set combo;
if BioSpm_Setting_v1r0=. and label=" " then delete;

if total=" " then  total="0";
if GroupVal1=" " then  GroupVal1="0";
if GroupVal2=" " then GroupVal2="0";
if Label="Collection Setting" then delete;
drop BioSpm_Setting_v1r0;
Label Label="Collection Setting";
rename GroupVal1=&type._Val1 GroupVal2=&type._Val2 Pvalue1=&type._PValue1 Pvalue2=&type._Pvalue2 total=&type._total;

/*keep GroupVal1 GroupVal2 label Total Pvalue1 pvalue2;*/
run;
%mend;
%coll_check(Blood);
%coll_check(Urine);
%coll_check(Mouth);
proc contents data=urine varnum; run;


/***deviation***
data recru_biospec_prod1;set recru_biospec_prod;MWTube1_BioCol_NotCollNotes=" ";
EDTATube1_Biocol_NotCollNotes=" ";run;*/


proc sort data=recru_biospec_prod;by RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 connect_id BioSpm_ColIDScan_v1r0;
run;

proc freq data=recru_biospec_prod; tables SSTube1_BioCol_Discard SSTube2_BioCol_Discard	ACDTube1_BioCol_Discard	EDTATube1_BioCol_Discard HepTube1_BioCol_Discard	
MWTube1_BioCol_Discard	UrineTube1_BioCol_Discard
SSTube1_BioCol_Deviation SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation
HepTube1_BioCol_Deviation MWTube1_BioCol_Deviation UrineTube1_BioCol_Deviation
/**/SSTube1_BioCol_NotCol SSTube2_BioCol_NotCol EDTATube1_BioCol_NotCol
HepTube1_BioCol_NotCol MWTube1_BioCol_NotCol ACDTube1_BioCol_NotCol  UrineTube1_BioCol_NotCol 
/list missing;run;

proc format;
value biotubefmt
1= "SSTube1"
2= "SSTube2"
3= "ACDTube1"
4= "EDTATube1"
5= "HepTube1"
6= "MWTube1"
7= "UrineTube1";
/*deviation Note is from EDTATube1_BioCol_DeviationNotes
**NotCol only from ACDTube1*/
data deviation_long; length BioTube_type_v1r0 $10.; 
set recru_biospec_prod;

by RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 connect_id BioSpm_ColIDScan_v1r0;
array tubeid {7} $ SSTube1_BioCol_TubeID SSTube2_BioCol_TubeID ACDTube1_BioCol_TubeID EDTATube1_BioCol_TubeID HepTube1_BioCol_TubeID 
MWTube1_BioCol_TubeID UrineTube1_BioCol_TubeID;
array tube_coll {7} SSTube1_BioCol_TubeColl SSTube2_BioCol_TubeCollected ACDTube1_BioCol_TubeCollected 
EDTATube1_Biocol_TubeCollected HepTube1_BioCol_TubeCollected MWTube1_BioCol_TubeCollected UrineTube1_BioCol_TubeCollected;
array notcoll {7} SSTube1_BioCol_NotCol	SSTube2_BioCol_NotCol ACDTube1_BioCol_NotCol EDTATube1_BioCol_NotCol 
HepTube1_BioCol_NotCol MWTube1_BioCol_NotCol UrineTube1_BioCol_NotCol;
array notcoll_Note {7} $ SSTube1_BioCol_NotCollNotes SSTube2_BioCol_NotCollNotes ACDTube1_BioCol_NotCollNotes EDTATube1_Biocol_NotCollNotes 
HepTube1_BioCol_NotCollNotes MWTube1_BioCol_NotCollNotes	UrineTube1_BioCol_NotCollNotes;
array deviatio {7} SSTube1_BioCol_Deviation SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation
HepTube1_BioCol_Deviation MWTube1_BioCol_Deviation UrineTube1_BioCol_Deviation;
***only EDTA  UrineTube1 with DeveiationNotes;
array deviNotes {7} $ SSTube1_BioCol_DeviationNotes SSTube2_BioCol_DeviationNotes
ACDTube1_BioCol_DeviationNotes EDTATube1_BioCol_DeviationNotes 
HepTube1_BioCol_DeviationNotes1	MWTube1_BioCol_DeviationNotes UrineTube1_BioCol_DeviationNotes;

array discard {7} SSTube1_BioCol_Discard SSTube2_BioCol_Discard	ACDTube1_BioCol_Discard	EDTATube1_BioCol_Discard HepTube1_BioCol_Discard	
MWTube1_BioCol_Discard	UrineTube1_BioCol_Discard;
***only ACD with notcollected and Notes;
do i =1 to 7;
BioCol_TubeID_v1r0=tubeid{i};
BioCol_Tube_Notcoll=notcoll{i};
BioCol_Tube_notcoll_Notes=notcoll_note{i};
BioCol_Tube_Collected=tube_coll{i};

BioCol_TubeDeviation_v1r0=deviatio{i};
BioCol_Tube_Discard=discard{i};
BioCol_Tube_DeviationNote=deviNotes{i};

if i >0 and i < 6 then BioTube_type_v1r0 ="Blood";
if i=6 then BioTube_type_v1r0 ="MouthWash";
if i=7 then BioTube_type_v1r0 ="Urine";
BioTube_ID_v1r0=i;
output;
end;
keep RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 connect_id BioSpm_ColIDScan_v1r0 bioTube_type_v1r0 BioTube_ID_v1r0 BioCol_TubeID_v1r0 BioCol_TubeDeviation_v1r0 
BioCol_Tube_DeviationNote BioCol_Tube_Discard BioCol_Tube_Notcoll BioCol_Tube_notcoll_Notes BioCol_Tube_Collected;
format BioCol_TubeDeviation_v1r0 DeviationSpecFmt. BioCol_Tube_Discard BioColDiscardFmt. BioCol_Tube_Collected BioColTubeCollFmt.
BioCol_Tube_Notcoll BioColRsnNotColFmt.;
attrib BioTube_ID_v1r0 format=biotubefmt. label="Tube Type";
run;
ods listing;
ods html close;

proc freq data=deviation_long;
table BioTube_type_v1r0*(BioCol_TubeDeviation_v1r0 BioCol_Tube_Discard BioCol_Tube_Notcoll)/list missing ;
format BioTube_ID_v1r0 biotubefmt.;run;
***                              BioTube_type_            BioCol_Tube                             Cumulative    Cumulative
                              v1r0                  Deviation_v1r0    Frequency     Percent     Frequency      Percent
                              ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                              Blood               No                       621       66.70           621        66.70
                              Blood               Yes                       44        4.73           665        71.43
                              MouthWash           No                       133       14.29           798        85.71
                              Urine               No                       126       13.53           924        99.25
                              Urine               Yes                        7        0.75           931       100.00


                              BioTube_type_           BioCol_Tube_                             Cumulative    Cumulative
                              v1r0                         Discard    Frequency     Percent     Frequency      Percent
                              ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                              Blood               No                       665       71.43           665        71.43
                              MouthWash           No                       133       14.29           798        85.71
                              Urine               No                       133       14.29           931       100.00


                            BioTube_type_                                                         Cumulative    Cumulative
                            v1r0                  BioCol_Tube_Notcoll    Frequency     Percent     Frequency      Percent
                            ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                            Blood                                   .         640       68.74           640        68.74
                            Blood               Short draw                      3        0.32           643        69.07
                            Blood               Participant attempted          22        2.36           665        71.43
                            MouthWash                               .         133       14.29           798        85.71
                            Urine                                   .         131       14.07           929        99.79
                            Urine               Participant attempted           2        0.21           931       100.00
******;
proc freq data=deviation_long;
table BioTube_ID_v1r0*(BioCol_TubeDeviation_v1r0 BioCol_Tube_Discard BioCol_Tube_Notcoll)/list missing ;
format BioTube_ID_v1r0 biotubefmt.;run;
***                                                    BioCol_Tube                             Cumulative    Cumulative
                               BioTube_ID_v1r0      Deviation_v1r0    Frequency     Percent     Frequency      Percent
                               ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                               SSTube1            No                       122       13.10           122        13.10
                               SSTube1            Yes                       11        1.18           133        14.29
                               SSTube2            No                       125       13.43           258        27.71
                               SSTube2            Yes                        8        0.86           266        28.57
                               ACDTube1           No                       118       12.67           384        41.25
                               ACDTube1           Yes                       15        1.61           399        42.86
                               EDTATube1          No                       127       13.64           526        56.50
                               EDTATube1          Yes                        6        0.64           532        57.14
                               HepTube1           No                       129       13.86           661        71.00
                               HepTube1           Yes                        4        0.43           665        71.43
                               MWTube1            No                       133       14.29           798        85.71
                               UrineTube1         No                       126       13.53           924        99.25
                               UrineTube1         Yes                        7        0.75           931       100.00


                                                      BioCol_Tube_                             Cumulative    Cumulative
                               BioTube_ID_v1r0             Discard    Frequency     Percent     Frequency      Percent
                               ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                               SSTube1            No                       133       14.29           133        14.29
                               SSTube2            No                       133       14.29           266        28.57
                               ACDTube1           No                       133       14.29           399        42.86
                               EDTATube1          No                       133       14.29           532        57.14
                               HepTube1           No                       133       14.29           665        71.43
                               MWTube1            No                       133       14.29           798        85.71
                               UrineTube1         No                       133       14.29           931       100.00


                                                                                                 Cumulative    Cumulative
                            BioTube_ID_v1r0      BioCol_Tube_Notcoll    Frequency     Percent     Frequency      Percent
                            ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                            SSTube1                                .         128       13.75           128        13.75
                            SSTube1            Participant attempted           5        0.54           133        14.29
                            SSTube2                                .         128       13.75           261        28.03
                            SSTube2            Short draw                      1        0.11           262        28.14
                            SSTube2            Participant attempted           4        0.43           266        28.57
                            ACDTube1                               .         127       13.64           393        42.21
                            ACDTube1           Short draw                      1        0.11           394        42.32
                            ACDTube1           Participant attempted           5        0.54           399        42.86
                            EDTATube1                              .         129       13.86           528        56.71
                            EDTATube1          Participant attempted           4        0.43           532        57.14
                            HepTube1                               .         128       13.75           660        70.89
                            HepTube1           Short draw                      1        0.11           661        71.00
                            HepTube1           Participant attempted           4        0.43           665        71.43
                            MWTube1                                .         133       14.29           798        85.71
                            UrineTube1                             .         131       14.07           929        99.79
                            UrineTube1         Participant attempted           2        0.21           931       100.00
*****;
/*for the deviation tubes*/
data dev; set deviation_long; where BioCol_TubeID_v1r0^=" " and BioCol_TubeDeviation_v1r0=353358909; run;/*n=51*/
/*%Table1_CTSPedia(DSName=dev, GroupVar= BioTube_type_v1r0 ,NumVars=,
                FreqVars =RcrtES_Site_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, 
FreqCell=N(CP), Print=Y,Label=L,Out=Biodev);*/
***Jul. 18, 2022 with totoal collection vs the deviation part;
%Table1_CTSPedia(DSName=deviation_long, GroupVar= BioCol_TubeDeviation_v1r0 ,NumVars=,
                FreqVars =/*BioCol_TubeDeviation_v1r0*/ RcrtES_Site_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, 
FreqCell=N(CP), Print=Y,Label=L,Out=Biodev1);
%Table1_CTSPedia(DSName=deviation_long, GroupVar= BioTube_ID_v1r0 ,NumVars=,
                FreqVars =BioCol_TubeDeviation_v1r0 RcrtES_Site_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, 
FreqCell=N(CP), Print=Y,Label=L,Out=Biodev2);

data dev1; set deviation_long; where BioCol_TubeID_v1r0^=" " and BioCol_Tube_Discard=353358909; run;/*n=0*/
%Table1_CTSPedia(DSName=dev1, GroupVar=BioTube_type_v1r0, NumVars=,
           FreqVars =BioCol_Tube_Discard RcrtES_Site_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, FreqCell=N(CP), 
Print=Y,Label=L,Out=Biodiscard);

/*Table 13-14*/
data nocoll;set deviation_long; where BioCol_TubeID_v1r0=" "; run;/*n=34*/
%Table1_CTSPedia(DSName=nocoll, GroupVar=BioTube_ID_v1r0  , NumVars=,
           FreqVars =BioCol_Tube_Notcoll,Mean=Y,Median=N,Total=C,Missing=Y,P=N, FreqCell=N(CP), 
Print=Y,Label=L,Out=BioNotColl2); 
proc freq data=nocoll;table BioCol_Tube_Notcoll*biotube_id_v1r0/missing list out=notcol noprint; run;/*16*/
proc print data=notcol noobs label;run;
***                                                                                              Percent of
                                                                                   Frequency       Total
                                             BioCol_Tube_Notcoll     Tube Type       Count       Frequency

                                                                .    SSTube1           1           2.9412
                                                                .    SSTube2           1           2.9412
                                                                .    ACDTube1          1           2.9412
                                                                .    EDTATube1         1           2.9412
                                                                .    HepTube1          1           2.9412
                                                                .    MWTube1           1           2.9412
                                                                .    UrineTube1        1           2.9412
                                            Short draw               SSTube2           1           2.9412
                                            Short draw               ACDTube1          1           2.9412
                                            Short draw               HepTube1          1           2.9412
                                            Participant attempted    SSTube1           5          14.7059
                                            Participant attempted    SSTube2           4          11.7647
                                            Participant attempted    ACDTube1          5          14.7059
                                            Participant attempted    EDTATube1         4          11.7647
                                            Participant attempted    HepTube1          4          11.7647
                                            Participant attempted    UrineTube1        2           5.8824
******;



%Table1_CTSPedia(DSName=deviation_long, GroupVar=BioTube_ID_v1r0 , NumVars=,
           FreqVars =BioCol_Tube_Notcoll RcrtES_Site_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, FreqCell=N(CP), 
Print=Y,Label=L,Out=BioNotColl3); 

proc freq data=nocoll;table BioCol_Tube_Notcoll*(BioTube_ID_v1r0 RcrtES_Site_v1r0)/list missing; run;
***
                                                                                                 Cumulative    Cumulative
                              BioCol_Tube_Notcoll    BioTube_ID_v1r0    Frequency     Percent     Frequency      Percent
                            ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                .    SSTube1                   1        2.94             1         2.94
                                                .    SSTube2                   1        2.94             2         5.88
                                                .    ACDTube1                  1        2.94             3         8.82
                                                .    EDTATube1                 1        2.94             4        11.76
                                                .    HepTube1                  1        2.94             5        14.71
                                                .    MWTube1                   1        2.94             6        17.65
                                                .    UrineTube1                1        2.94             7        20.59
                            Short draw               SSTube2                   1        2.94             8        23.53
                            Short draw               ACDTube1                  1        2.94             9        26.47
                            Short draw               HepTube1                  1        2.94            10        29.41
                            Participant attempted    SSTube1                   5       14.71            15        44.12
                            Participant attempted    SSTube2                   4       11.76            19        55.88
                            Participant attempted    ACDTube1                  5       14.71            24        70.59
                            Participant attempted    EDTATube1                 4       11.76            28        82.35
                            Participant attempted    HepTube1                  4       11.76            32        94.12
                            Participant attempted    UrineTube1                2        5.88            34       100.00


                                                                                                         Cumulative    Cumulative
                      BioCol_Tube_Notcoll                   RcrtES_Site_v1r0    Frequency     Percent     Frequency      Percent
                    ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                        .    Marshfield Clinic Health System           7       20.59             7        20.59
                    Short draw               HealthPartners                            1        2.94             8        23.53
                    Short draw               University of Chicago Medicine            2        5.88            10        29.41
                    Participant attempted    Henry Ford Health System                  2        5.88            12        35.29
                    Participant attempted    University of Chicago Medicine           22       64.71            34       100.00
******;

data deviation_long; set deviation_long;
if BioCol_TubeID_v1r0=" " and BioCol_Tube_Collected=104430631 and BioCol_Tube_Notcoll=. then BioCol_Tube_Notcoll2=999999999;
else if BioCol_TubeID_v1r0 =" " and BioCol_Tube_Collected=104430631 and BioCol_Tube_Notcoll >0 then BioCol_Tube_Notcoll2=BioCol_Tube_Notcoll;
format BioCol_Tube_Notcoll2 TubeNotCollFmt. ;
run;


%Table1_CTSPedia(DSName=deviation_long, GroupVar=BioCol_Tube_Notcoll2 , NumVars=,
           FreqVars =BioTube_ID_v1r0 RcrtES_Site_v1r0 ,Mean=Y,Median=N,Total=C,Missing=Y,P=N, FreqCell=N(CP), 
Print=Y,Label=L,Out=BioNotColl4); /*table 13*/

data tmp4;set recru_biospec_prod;
/*SSTube1_BioCol_NotCollNotes=" ";
SSTube2_BioCol_NotCollNotes=" ";HepTube1_BioCol_NotCollNotes=" ";*/
MWTube1_BioCol_NotCollNotes=" ";
EDTATube1_Biocol_NotCollNotes=" ";
run;
proc freq data=recru_biospec_prod;
table SSTube1_BioCol_NotCollNotes ACDTube1_BioCol_NotCollNotes
SSTube2_BioCol_NotCollNotes
EDTATube1_Biocol_NotCollNotes
HepTube1_BioCol_NotCollNotes
MWTube1_BioCol_NotCollNotes;run;
proc sort data=tmp4;
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0
BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation 
HepTube1_BioCol_Deviation UrineTube1_BioCol_Deviation MWTube1_BioCol_Deviation;run;
proc transpose data=tmp4 out=Tubes_deviation prefix=Tubetype;
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0
BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation 
HepTube1_BioCol_Deviation UrineTube1_BioCol_Deviation MWTube1_BioCol_Deviation;
var SSTube1_BioCol_TubeID SSTube2_BioCol_TubeID ACDTube1_BioCol_TubeID EDTATube1_BioCol_TubeID HepTube1_BioCol_TubeID UrineTube1_BioCol_TubeID MWTube1_BioCol_TubeID;
run;
data Tubes_deviation1;
set Tubes_deviation;
rename _Name_ = Type_BioCol_TubeID;
drop _label_; 
run;/*n=931*/

/*tables 13-15 for Not Collected Notes*/
proc sort data=tmp4;
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation 
SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation HepTube1_BioCol_Deviation UrineTube1_BioCol_Deviation	MWTube1_BioCol_Deviation;run;
proc transpose data=tmp4 out=Tubes_NotCollected prefix=NotCollection;
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation 
SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation HepTube1_BioCol_Deviation 
UrineTube1_BioCol_Deviation	MWTube1_BioCol_Deviation;
var SSTube1_BioCol_NotCol SSTube2_BioCol_NotCol ACDTube1_BioCol_NotCol EDTATube1_BioCol_NotCol 
HepTube1_BioCol_NotCol UrineTube1_BioCol_NotCol MWTube1_BioCol_NotCol;
run;/*931*/
data Tubes_NotCollected;set Tubes_NotCollected;
rename _Name_= BioTube_NotCol_Type;
run;

proc transpose data=tmp4 out=Notes_NotCollected prefix=NotColl_notes;
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation 
SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation 
HepTube1_BioCol_Deviation UrineTube1_BioCol_Deviation	MWTube1_BioCol_Deviation;
var SSTube1_BioCol_NotCollNotes SSTube2_BioCol_NotCollNotes ACDTube1_BioCol_NotCollNotes EDTATube1_Biocol_NotCollNotes HepTube1_BioCol_NotCollNotes 
UrineTube1_BioCol_NotCollNotes MWTube1_BioCol_NotCollNotes;
run;

proc sort data=Tubes_NotCollected; by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation 
HepTube1_BioCol_Deviation UrineTube1_BioCol_Deviation MWTube1_BioCol_Deviation;run;

proc sort data=Notes_NotCollected;
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation 
SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation 
HepTube1_BioCol_Deviation UrineTube1_BioCol_Deviation	MWTube1_BioCol_Deviation;run;

data Tubes_NotColl_NotColNotes;merge Tubes_NotCollected (in =a) Notes_NotCollected (in=b);
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation 
HepTube1_BioCol_Deviation	UrineTube1_BioCol_Deviation	MWTube1_BioCol_Deviation; if a=b; 
format NotCollection1 BioColRsnNotColFmt.;run;

data tubeID_NotColl_NotColNotes; merge Tubes_deviation1 (in=a) Tubes_NotColl_NotColNotes (in=b);
by Connect_id BioSpm_ColIDScan_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 SSTube1_BioCol_Deviation SSTube2_BioCol_Deviation ACDTube1_BioCol_Deviation EDTATube1_BioCol_Deviation 
HepTube1_BioCol_Deviation	UrineTube1_BioCol_Deviation	MWTube1_BioCol_Deviation; if a=b; 
run;
proc freq data=tubeID_NotColl_NotColNotes; table tubetype1/list missing; run;
data NotColl_notes; set tubeID_NotColl_NotColNotes;
if tubetype1=" " then NotCollNote=1;
else NotCollNote=0;
/*label tubetype1="Not Collected=Short draw";*/
run;

proc freq data=NotColl_notes ; 
table NotCollNote*BioSpm_Setting_v1r0*Type_BioCol_TubeID*RcrtES_Site_v1r0*BioSpm_Location_v1r0 /list missing out=short_ID; 
/*where NotCollNote=1;*/
run;***short_id n=58**;

proc freq data=NotColl_notes ; 
table BioSpm_Setting_v1r0*Type_BioCol_TubeID*RcrtES_Site_v1r0*BioSpm_Location_v1r0 /list missing out=total_ID; 
run;
/*where NotCollNote=1;*/

proc sort data=total_id; by  BioSpm_Setting_v1r0 BioSpm_Location_v1r0 RcrtES_Site_v1r0;run;
proc transpose data=total_id out=notes_total suffix=Coll;
by BioSpm_Setting_v1r0 BioSpm_Location_v1r0 RcrtES_Site_v1r0 ;
id Type_BioCol_TubeID;
var count; /*SSTube1_BioCol_NotCollNotes SSTube2_BioCol_NotCollNotes EDTATube1_Biocol_NotCollNotes HepTube1_BioCol_NotCollNotes 
MWTube1_BioCol_NotCollNotes	UrineTube1_BioCol_NotCollNotes*/
run;

proc sort data=short_id; by  NotCollNote BioSpm_Setting_v1r0 BioSpm_Location_v1r0 RcrtES_Site_v1r0;run;
proc transpose data=short_id out=notes_notcol suffix=Coll;
by NotCollNote BioSpm_Setting_v1r0 BioSpm_Location_v1r0 RcrtES_Site_v1r0 ;
id Type_BioCol_TubeID;
var count; /*SSTube1_BioCol_NotCollNotes SSTube2_BioCol_NotCollNotes EDTATube1_Biocol_NotCollNotes HepTube1_BioCol_NotCollNotes 
MWTube1_BioCol_NotCollNotes	UrineTube1_BioCol_NotCollNotes*/
run;/*n=10*/
proc contents data=notes_notcol; run;
***                    #    Variable                        Type    Len    Format      Informat    Label

                    4    ACDTube1_BioCol_TubeIDColl      Num       8
                    5    EDTATube1_BioCol_TubeIDColl     Num       8
                    6    HepTube1_BioCol_TubeIDColl      Num       8
                    7    MWTube1_BioCol_TubeIDColl       Num       8
                    1    RcrtES_Site_v1r0                Num       8    SITEFMT.    BEST9.      Site
                    8    SSTube1_BioCol_TubeIDColl       Num       8
                    9    SSTube2_BioCol_TubeIDColl       Num       8
                   10    UrineTube1_BioCol_TubeIDColl    Num       8
                    3    _LABEL_                         Char     40                            LABEL OF FORMER VARIABLE
                    2    _NAME_                          Char      8                            NAME OF FORMER VARIABLE
******;
proc sort data=notes_notcol; by NotCollNote  BioSpm_Setting_v1r0 BioSpm_Location_v1r0 RcrtES_Site_v1r0;run;
proc sql;
create table notes_notcol1 as 
select
a. *, b. ACDTube1_BioCol_TubeIDColl as TotalTube1_BioCol_TubeIDColl
from
notes_notcol (where=(NotCollNote=0)) a
right join
notes_total b
on a. BioSpm_Location_v1r0=b. BioSpm_Location_v1r0 and a. RcrtES_Site_v1r0 = b. RcrtES_Site_v1r0
order by b. BioSpm_Location_v1r0;
run;
quit;
data notes_notcol1;
set notes_notcol1;
total_notcol=0;
by NotCollNote  BioSpm_Setting_v1r0 BioSpm_Location_v1r0;
total_tubesColl=SSTube1_BioCol_TubeIDColl+SSTube2_BioCol_TubeIDColl+ACDTube1_BioCol_TubeIDColl+EDTATube1_BioCol_TubeIDColl+HepTube1_BioCol_TubeIDColl
+UrineTube1_BioCol_TubeIDColl+MWTube1_BioCol_TubeIDColl;
array col {7} SSTube1_BioCol_TubeIDColl SSTube2_BioCol_TubeIDColl ACDTube1_BioCol_TubeIDColl EDTATube1_BioCol_TubeIDColl
HepTube1_BioCol_TubeIDColl MWTube1_BioCol_TubeIDColl UrineTube1_BioCol_TubeIDColl;

array notcol {7} SST1 SST2 ACD EDTA Heparin Mouthwash Urine;
do i=1 to 7;
notcol{i}=TotalTube1_BioCol_TubeIDColl-col{i};
total_notcol=notcol{i}+total_notcol;
end;
label SST1="SSTube1_BioCol_NotCol"  SST2="SSTube2_BioCol_NotCol"
Heparin="HepTube1_BioCol_NotCol" EDTA="EDTATube1_BioCol_NotCol"
ACD="ACDTube1_BioCol_NotCol" Urine="UrineTube1_BioCol_NotCol" Mouthwash="MWTube1_BioCol_NotCol"
total_tubesColl="Total Collected " TotalTube1_BioCol_TubeIDColl="Total tubes to be collected per type"
total_notcol="Total tubes not Collected"; 
where NotCollNote =0;
run;/*n=6*/
proc print data=notes_notcol1 noobs label;
var BioSpm_Setting_v1r0 RcrtES_Site_v1r0 BioSpm_Location_v1r0 SST1 SST2 ACD EDTA Heparin Mouthwash Urine TotalTube1_BioCol_TubeIDColl
total_tubesColl total_notcol;run;
proc freq data=notes_notcol; table NotCollNote/missing list; run;
***                                                                                  Cumulative    Cumulative
                                           NotCollNote    Frequency     Percent     Frequency      Percent
                                           ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                     0           6       60.00             6        60.00
                                                     1           4       40.00            10       100.00
******;
proc sql;
create table notcol_total as
select BioSpm_Setting_v1r0,
sum(SST1) as SST1,
sum(sst2) as SST2,
sum(acd) as acd,
sum(edta) as edta,
sum(heparin) as heparin,
sum(mouthwash) as mouthwash,
sum(urine) as urine,
sum(total_tubesColl) as total_tubesColl,
sum(total_notcol) as total_notcol
from Notes_notcol1
group by BioSpm_Setting_v1r0;
run;

data notcol_allsite;
set Notes_notcol1 notcol_total;
if Mouthwash=. then Mouthwash=0;
run;
proc format;
	VALUE Site1Fmt
			531629870 = "HealthPartners"
			548392715 = "Henry Ford Health System"
			125001209 = "Kaiser Permanente Colorado"
			327912200 = "Kaiser Permanente Georgia"
			300267574 = "Kaiser Permanente Hawaii"
			452412599 = "Kaiser Permanente Northwest"
			303349821 = "Marshfield Clinic Health System"
			657167265 = "Sanford Health"
			809703864 = "Unviersity of Chicago Medicine"
			517700004 = "National Cancer Institute"
			13 = "National Cancer Institute"
			181769837 = "Other"
			. = "Total";
proc print data=notcol_allsite noobs label;
var BioSpm_Setting_v1r0 RcrtES_Site_v1r0 SST1 SST2 ACD EDTA Heparin Mouthwash Urine TotalTube1_BioCol_TubeIDColl
total_notcol;
format RcrtES_Site_v1r0 site1fmt.; run;
***                                                                                                                          Total tubes
                                                SSTube1_  SSTube2_  ACDTube1_  EDTATube1_  HepTube1_  MWTube1_     Urine       to be       Total
   Collection                                    BioCol_   BioCol_   BioCol_     BioCol_    BioCol_    BioCol_   Tube1_Bio   collected   tubes not
    Setting    Site                              NotCol    NotCol     NotCol     NotCol      NotCol    NotCol   Col_NotCol    per type   Collected

    Research   Sanford Health                       0         0         0           0          0          0          0            9           0
    Research   Marshfield Clinic Health System      1         1         1           1          1          1          1           22           7
    Research   Marshfield Clinic Health System      0         0         0           0          0          0          0            8           0
    Research   Unviersity of Chicago Medicine       4         5         4           4          5          0          2           19          24
    Research   HealthPartners                       0         0         1           0          0          0          0           56           1
    Research   Henry Ford Health System             1         0         1           0          0          0          0           19           2
    Research   Total                                6         6         7           5          6          1          3            .          34
********;
data tmp4; set tmp4; 
ACDTube1_BioCol_DeviationNotes= " ";
MWTube1_BioCol_DeviationNotes =" "; run;
proc sort data=tmp4; by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 SSTube1_BioCol_TubeID SSTube1_BioCol_TubeColl 
SSTube1_BioCol_Deviation SSTube1_BioCol_DeviationNotes; run;
proc transpose data=tmp4 out=sstube1_devia_long prefix=deviation;
by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 SSTube1_BioCol_TubeID SSTube1_BioCol_TubeColl 
SSTube1_BioCol_Deviation SSTube1_BioCol_DeviationNotes ;
var /*SSTube1_BioCol_NotCollNotes SSTube1_BioCol_TubeID SSTube1_BioCol_NotCol
SSTube1_BioCol_Discard*/
SSTube1_Deviation_Broken
SSTube1_Deviation_ClotL
SSTube1_Deviation_ClotS
SSTube1_Deviation_Discard
SSTube1_Deviation_Gel
SSTube1_Deviation_Hemolyzed
SSTube1_Deviation_Leak
SSTube1_Deviation_LowVol
SSTube1_Deviation_MislabelD
/*SSTube1_Deviation_MisLabeled*/
SSTube1_Deviation_MislabelR
SSTube1_Deviation_NotFound
SSTube1_Deviation_Other
SSTube1_Deviation_OutContam
SSTube1_Deviation_SpeedH
SSTube1_Deviation_SpeedL
SSTube1_Deviation_TempH
SSTube1_Deviation_TempL
SSTube1_Deviation_TimeL
SSTube1_Deviation_TimeS
SSTube1_Deviation_TubeSz;
run;
option ls=160;
proc freq data=sstube1_devia_long;table _label_*Deviation1/list missing; 
where _label_ not in ("SSTube1_BioCol_Discard","SSTube1_BioCol_NotCol");where SSTube1_BioCol_Deviation=353358909;run;

proc sort data=tmp4; by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 SSTube2_BioCol_TubeID 
SSTube2_BioCol_TubeCollected SSTube2_BioCol_Deviation SSTube2_BioCol_DeviationNotes; run;
proc transpose data=tmp4 out=sstube2_devia_long prefix=deviation;
by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 SSTube2_BioCol_TubeID SSTube2_BioCol_TubeCollected 
SSTube2_BioCol_Deviation SSTube2_BioCol_DeviationNotes;
var /*SSTube2_BioCol_TubeID  SSTube2_BioCol_NotCollNotes
SSTube2_BioCol_Discard
SSTube2_BioCol_NotCol
*/
SSTube2_Deviation_Broken
SSTube2_Deviation_ClotL
SSTube2_Deviation_ClotS
SSTube2_Deviation_Discard
SSTube2_Deviation_Gel
SSTube2_Deviation_Hemolyzed
SSTube2_Deviation_Leak
SSTube2_Deviation_LowVol
SSTube2_Deviation_MislabelD
/*SSTube2_Deviation_MisLabeled*/
SSTube2_Deviation_MislabelR
SSTube2_Deviation_NotFound
SSTube2_Deviation_Other
SSTube2_Deviation_OutContam
SSTube2_Deviation_SpeedH
SSTube2_Deviation_SpeedL
SSTube2_Deviation_TempH
SSTube2_Deviation_TempL
SSTube2_Deviation_TimeL
SSTube2_Deviation_TimeS
SSTube2_Deviation_TubeSz;
run;

proc sort data=tmp4; by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 ACDTube1_BioCol_TubeID ACDTube1_BioCol_TubeCollected  
ACDTube1_BioCol_Deviation ACDTube1_BioCol_DeviationNotes; run;
proc transpose data=tmp4 out=ADTtube1_devia_long prefix=deviation;
by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 ACDTube1_BioCol_TubeID ACDTube1_BioCol_TubeCollected 
ACDTube1_BioCol_Deviation ACDTube1_BioCol_DeviationNotes;
var /* ACDTube1_BioCol_NotCollNotes
ACDTube1_BioCol_Discard
ACDTube1_BioCol_NotCol*/

ACDTube1_Deviation_Broken
ACDTube1_Deviation_Discard
ACDTube1_Deviation_Hemolyzed
ACDTube1_Deviation_Leak
ACDTube1_Deviation_LowVol
ACDTube1_Deviation_MislabelD
/*ACDTube1_Deviation_MisLabeled*/
ACDTube1_Deviation_MislabelR
ACDTube1_Deviation_NotFound
ACDTube1_Deviation_Other
ACDTube1_Deviation_OutContam
ACDTube1_Deviation_TempH
ACDTube1_Deviation_TempL
ACDTube1_Deviation_TubeSz;
run;

proc sort data=tmp4; by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 EDTATube1_BioCol_TubeID EDTATube1_BioCol_TubeCollected 
EDTATube1_BioCol_Deviation EDTATube1_BioCol_DeviationNotes; run;
proc transpose data=tmp4 out=EDTAtube1_devia_long prefix=deviation;
by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 EDTATube1_BioCol_TubeID EDTATube1_BioCol_TubeCollected 
EDTATube1_BioCol_Deviation EDTATube1_BioCol_DeviationNotes ;
var /*EDTATube1_Biocol_NotCollNotes
EDTATube1_BioCol_Discard
EDTATube1_BioCol_NotCol*/

EDTATube1_Deviation_Broken
EDTATube1_Deviation_Discard
EDTATube1_Deviation_Hemolyzed
EDTATube1_Deviation_Leak
EDTATube1_Deviation_LowVol
EDTATube1_Deviation_MislabelD
/*EDTATube1_Deviation_MisLabeled*/
EDTATube1_Deviation_MislabelR
EDTATube1_Deviation_NotFound
EDTATube1_Deviation_Other
EDTATube1_Deviation_OutContam
EDTATube1_Deviation_TempH
EDTATube1_Deviation_TempL
EDTATube1_Deviation_TubeSz; 
run;

proc sort data=tmp4; by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 HepTube1_BioCol_TubeID HepTube1_BioCol_TubeCollected 
HepTube1_BioCol_Deviation HepTube1_BioCol_DeviationNotes; run;
proc transpose data=tmp4 out=heptube1_devia_long prefix=deviation;
by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 HepTube1_BioCol_TubeID HepTube1_BioCol_TubeCollected
HepTube1_BioCol_Deviation HepTube1_BioCol_DeviationNotes;
var /* HepTube1_BioCol_NotCollNotes
HepTube1_BioCol_Discard
HepTube1_BioCol_NotCol
*/
HepTube1_Deviation_Broken
HepTube1_Deviation_Discard
HepTube1_Deviation_Hemolyzed
HepTube1_Deviation_Leak
HepTube1_Deviation_LowVol
HepTube1_Deviation_MislabelD
/*HepTube1_Deviation_MisLabeled*/
HepTube1_Deviation_MislabelR
HepTube1_Deviation_NotFound
HepTube1_Deviation_Other
HepTube1_Deviation_OutContam
HepTube1_Deviation_TempH
HepTube1_Deviation_TempL
HepTube1_Deviation_TubeSz;
run;

proc sort data=tmp4; by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 HepTube1_BioCol_TubeID UrineTube1_BioCol_TubeCollected 
UrineTube1_BioCol_Deviation UrineTube1_BioCol_DeviationNotes; run;
proc transpose data=tmp4 out=urinetube1_devia_long prefix=deviation;
by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 UrineTube1_BioCol_TubeID UrineTube1_BioCol_TubeCollected 
UrineTube1_BioCol_Deviation UrineTube1_BioCol_DeviationNotes;
var /*UrineTube1_BioCol_Deviation

UrineTube1_BioCol_Discard
UrineTube1_BioCol_NotCol*/
/*UrineTube1_BioCol_NotCollNotes UrineTube1_BioCol_TubeID*/
UrineTube1_Deviation_Broken
UrineTube1_Deviation_Leak
UrineTube1_Deviation_LowVol
UrineTube1_Deviation_MislabelD
/*UrineTube1_Deviation_MisLabeled*/
UrineTube1_Deviation_MislabelR
UrineTube1_Deviation_NotFound
UrineTube1_Deviation_Other
UrineTube1_Deviation_OutContam
UrineTube1_Deviation_TempH
UrineTube1_Deviation_TempL
UrineTube1_Deviation_UrVol; run;

proc sort data=tmp4; by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 MWTube1_BioCol_TubeID MWTube1_BioCol_TubeCollected 
MWTube1_BioCol_Deviation MWTube1_BioCol_DeviationNotes; run;
proc transpose data=tmp4 out=MWtube1_devia_long prefix=deviation;
by connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0 MWTube1_BioCol_TubeID MWTube1_BioCol_TubeCollected 
MWTube1_BioCol_Deviation MWTube1_BioCol_DeviationNotes;
var /*MWTube1_BioCol_Deviation MWTube1_BioCol_NotCollNotes

MWTube1_BioCol_Discard
MWTube1_BioCol_NotCol*/

/*MWTube1_BioCol_TubeID
MWTube1_Deviation_MisLabeled*/
MWTube1_Deviation_Broken
MWTube1_Deviation_Leak
MWTube1_Deviation_LowVol
MWTube1_Deviation_MislabelD

MWTube1_Deviation_MislabelR
MWTube1_Deviation_MWUnder30s
MWTube1_Deviation_NotFound
MWTube1_Deviation_Other
MWTube1_Deviation_OutContam; run;


%macro all_deviation(data,type, tubeid,tubedev,tubecoll,devnotes);
data dev; length biospecimen $10.;
set &data;
BioCol_TubeID_v1r0=&tubeid;BioCol_TubeDeviation_v1r0=&tubedev;BioCol_TubeCollected_v1r0=&tubecoll;
BioCol_DeviationNotes=&devnotes;
biospecimen="&type";drop &tubeid &tubedev &tubecoll;
run;

proc append base=BioCol_deviation data=dev force; run;
%mend;
%all_deviation(sstube1_devia_long, blood, SSTube1_BioCol_TubeID,SSTube1_BioCol_Deviation,SSTube1_BioCol_TubeColl, SSTube1_BioCol_DeviationNotes);
%all_deviation(sstube2_devia_long, blood, SSTube2_BioCol_TubeID, SSTube2_BioCol_Deviation,SSTube2_BioCol_TubeCollected, SSTube2_BioCol_DeviationNotes);
%all_deviation(ADttube1_devia_long, blood, ACDTube1_BioCol_TubeID, ACDTube1_BioCol_Deviation,ACDTube1_BioCol_TubeCollected,);
%all_deviation(EDTAtube1_devia_long, blood, EDTATube1_BioCol_TubeID, EDTATube1_BioCol_Deviation,EDTATube1_BioCol_TubeCollected, EDTATube1_BioCol_DeviationNotes);
%all_deviation(Heptube1_devia_long, blood, HepTube1_BioCol_TubeID, HepTube1_BioCol_Deviation,HepTube1_BioCol_TubeCollected, HepTube1_BioCol_DeviationNotes);
%all_deviation(Urinetube1_devia_long, urine, UrineTube1_BioCol_TubeID, UrineTube1_BioCol_Deviation,UrineTube1_BioCol_TubeCollected,UrineTube1_BioCol_DeviationNotes);
%all_deviation(MWtube1_devia_long, mouthwash, MWTube1_BioCol_TubeID, MWTube1_BioCol_Deviation,MWTube1_BioCol_TubeCollected,);

data BioCol_deviation;set BioCol_deviation;
format deviation1 DeviationSpecFmt. BioCol_TubeDeviation_v1r0 DeviationSpecFmt. BioCol_TubeCollected_v1r0 BioColTubeCollFmt.;
run;/*n=14364*/


data biospeci_deviation; length bio_type $10.;
set BioCol_deviation;
if scan(_name_, 1, "_")="UrineTube1" then bio_type="Urine";
else if scan(_name_, 1, "_")="MWTube1" then bio_type="MouthWash";
else bio_type="Blood"; drop biospecimen;
if deviation1=353358909 then output;
format deviation1 DeviationSpecFmt. BioCol_TubeDeviation_v1r0 DeviationSpecFmt. BioCol_TubeCollected_v1r0 BioColTubeCollFmt.;
run;/*n=54*/

/***for table 12** deviation note by type****/
proc freq data=biospeci_deviation;
table bio_type*BioCol_DeviationNotes*_label_ /list missing out=dev_notes;where connect_id^=9122429867 and deviation1=353358909; run;
*** bio_type    BioCol_DeviationNotes                              _LABEL_
 ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
 Blood                                                          EDTA Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Blood                                                          Heparin Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Blood                                                          Serum Separator Tube 1- Deviation Centrifuge Too Short
 Blood                                                          Serum Separator Tube 1- Deviation Hemolyzed
 Blood                                                          Serum Separator Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Blood                                                          Serum Separator Tube 2- Deviation Centrifuge Too Short
 Blood                                                          Serum Separator Tube 2- Deviation Hemolyzed
 Blood                                                          Serum Separator Tube 2- Deviation Low Volume-(tube/container partially filled but still usable)
 Blood       Pt attempted draw but vein blood flow stopped b    EDTA Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Blood       Tube is about half full                            Heparin Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Blood       low volume in tube as well as hemolysis present    Serum Separator Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Blood       severely hemolyzed                                 Serum Separator Tube 1- Deviation Hemolyzed
 Urine                                                          Urine Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Urine       Pt had trouble leaving specimen                    Urine Tube 1- Deviation Low Volume-(tube/container partially filled but still usable)
 Urine       Urine that was obtained was not a clean catch      Urine Tube 1- Deviation Other
 Urine       could not collect                                  Urine Tube 1- Deviation Other
 Urine       did not perform clean catch                        Urine Tube 1- Deviation Other

                                                                                Cumulative    Cumulative
                                                       Frequency     Percent     Frequency      Percent
                                                       ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ
                                                              5        9.26             5         9.26
                                                              3        5.56             8        14.81
                                                              1        1.85             9        16.67
                                                              6       11.11            15        27.78
                                                              3        5.56            18        33.33
                                                              2        3.70            20        37.04
                                                              8       14.81            28        51.85
                                                              8       14.81            36        66.67
                                                              1        1.85            37        68.52
                                                              1        1.85            38        70.37
                                                              1        1.85            39        72.22
                                                              1        1.85            40        74.07
                                                              6       11.11            46        85.19
                                                              2        3.70            48        88.89
                                                              2        3.70            50        92.59
                                                              2        3.70            52        96.30
                                                              2        3.70            54       100.00
*******;

PROC PRINT DATA=biospeci_deviation;
/*var Connect_id BioSpm_ColIDScan_v1r0 BioSpm_Location_v1r0  BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 _Name_ _Label_ Deviation1;*/
where connect_id^=9122429867;
RUN;
****May 25, 2022, here are the comments from Michelle on the updated metrics below****
Table 2: Please shorten column headers so the columns can be viewed side by side on the page
Tables 4, 6, 8: We need the row percent rather than the column percent
Check all of the titles to fix the spelling of ?ablr?and make Participants plural with an s
Pie chart called Table 11:, the title is wrong. Please look at the other document with Nicole and my comments for the correct title
We don? need the other table 11, table 12 or table 13A (settings for sample collections separately for blood, urine, mouthwash- please delete
Table 13b: Fix the spelling of urine in the title
Table 14: It? not clear to me how to interpret this. Does the 8 on the first row mean 8 people checked in for a baseline visit and did not give any blood?  The way you have Table 15 is clearer. Can you make table 14 look like table 15 but the header in the first column would just be ?ny blood collected?which would = no
Table 14: Needs ?aseline?before ?heck-ins?in title and needs ?ll sites?in title
Table 15: Needs all sites in title
Table 16: Need to add the total number of tubes of each type collected and the percentage needs to be out of the total number of tubes collected of the type, not the percents you have now
Table 17: same comments as Table 16
*****************;
ods html;
/*ods pdf file="\\Mac\Home\Documents\CONNECT_projects\Biospecimen_Feb2022\Jing_projects\biospecQC_03082022\SASoutputs\biospecimen_metrics_baseline_participants_Prod_06242022.pdf";*/
/*ods pdf file="\\Mac\Home\Documents\CONNECT_projects\Biospecimen_Feb2022\Jing_projects\biospecQC_03082022\SASoutputs\biospecimen_metrics_baseline_participants_Prod_v2_07182022.pdf";
ods pdf file="\\Mac\Home\Documents\CONNECT_projects\Biospecimen_Feb2022\Jing_projects\biospecQC_03082022\SASoutputs\biospecimen_metrics_baseline_participants_Prod_v3_07182022.pdf";
ods pdf file="\\Mac\Home\Documents\CONNECT_projects\Biospecimen_Feb2022\Jing_projects\biospecQC_03082022\SASoutputs\biospecimen_metrics_baseline_participants_Prod_v4_07182022.pdf";*/
ods pdf file="\\Mac\Home\Documents\CONNECT_projects\Biospecimen_Feb2022\Jing_projects\biospecQC_03082022\SASoutputs\biospecimen_metrics_baseline_participants_Prod_08082022.pdf";

ods gridded column=6;
/*proc print data=biospec_zero noobs label;
title "Table 1. Percent (and number) of verified participants with baseline biospecimen collections by site";
var label GroupVal1 GroupVal2 total;run;
Table 1.*/
data table1;set biospec_zero;
site=label;if label="Site" then delete;
 run;
proc report data=table1  split='/' nowd ;
title "Table 1.Percent (and number) of verified participants with baseline biospecimen collections by site";
columns  site  GroupVal1 GroupVal2 Total;
define site/ "Site " width=36 left;
define  GroupVal1/"No Samples Collected" left width=20;
define GroupVal2 /"Any Samples Collected" center width=20; 
define Total/"Total " center width=10; 
run;

/*Table 2.*/
title "Table 2. Percent (and number) of verified participants with baseline blood collected by site";
/*%Table1Print_CTSPedia(DSname=Biospec_one, Space=Y);*/
data table2;set biospec_one;
site=label;if label="Site" then delete;
 run;
proc report data=Table2  split='/' nowd ;
columns  site  GroupVal1 GroupVal2 Total;
define site/ "Site " width=36 left;
define  GroupVal1/"Blood Not Collected" left width=20;
define GroupVal2 /"Blood Collected" center width=20; 
define Total/"Total" center width=10; 
run;

/*Table 3.*/
title "Table 3. Percent (and number) of verified participants with baseline urine collected by site";
/*%Table1Print_CTSPedia(DSname=Biospec_two, Space=Y);*/
data table3;set biospec_two;
site=label;if label="Site" then delete;
 run;
proc report data=table3  split='/' nowd ;
columns  site  GroupVal1 GroupVal2 Total;
define site/ "Site" width=36 left;
define  GroupVal1/"No Urine Collected" left width=20;
define GroupVal2 /"Urine Collected" center width=20; 
define Total/"Total " center width=10; 
run;
/*Table 4. */
title "Table 4. Percent (and number) of verified participants with baseline mouthwash collected by site";
/*%Table1Print_CTSPedia(DSname=Biospec_three, Space=Y);*/
data table4;set biospec_three;
site=label;if label="Site" then delete;
 run;
proc report data=table4  split='/' nowd ;
columns  Site GroupVal1 GroupVal2 Total;
define site/ "Site" width=36 left;
define  GroupVal1/"No Mouthwash Collected" left width=20;
define GroupVal2 /"Mouthwash Collected" center width=20; 
define Total/"Total" center width=10; 
run;

/*Table 5. */
proc freq data=tmp;
tables BioFin_BaseBloodCol_v1r0*BioFin_baseUrineCol_v1r0*BioFin_BaseMouthCol_v1r0/list cumcol missing noprint out=threebio;
/*where connect_id=connectbio_id;*/
run;
data threebio1;
set threebio end=last_obs;
retain cumcount cumperc; length perc_char $8.;length cumpct_char $10.;
cumcount=sum(cumcount,count);cumperc=sum(percent,cumperc);
perc_char=put(round(percent,0.01), 4.2)||'%';
cumpct_char=put(round(cumperc,0.01),4.2)||'%';
label BioFin_BaseBloodCol_v1r0="Blood Collected?"
	BioFin_baseUrineCol_v1r0="Urine Collected?"
	BioFin_BaseMouthCol_v1r0="Mouthwash Collected?"
	perc_char="Percent of Total Frequency"
	cumcount="Cumulative Frequency"
	cumpct_char="Cumulative Percent";
run;
proc print data=threebio1 noobs label;
title "Table 5. Percent (and number) of verified participants with all baseline biospecimens collected";
var BioFin_BaseBloodCol_v1r0 BioFin_baseUrineCol_v1r0 BioFin_BaseMouthCol_v1r0 count percent cumcount cumpct_char;
run;

/*title "Table 6. Percent (N) of verified participants with all the blood tubes collected all sites 0718202";
%Table1Print_CTSPedia(DSname=Biocmp_blood, Space=Y);*/
/*Table 6.*/
title "Table 6. Percent (and number) of verified participants with all blood tubes collected by site";
/*%Table1Print_CTSPedia(DSname=Biospec_seven, Space=Y);*/
data table6;set biospec_seven;
site=label;if label="Site" then delete;
 run;
proc report data=table6  split='/' nowd ;
columns  site GroupVal1 GroupVal2 Total;
define site/ "Site" width=36 left;
define  GroupVal1/"Partial Blood Tubes Collected" left width=20;
define GroupVal2 /"All Blood Tubes Collected" center width=20; 
define Total/"Total" center width=10; 
run;


proc format;
 value typeyesnofmt
 0 = "no blood, no urine, no mouthwash"
 1 = "only blood"
 2 = "only urine"
 3 = "only mouthwash"
 4 = "blood and urine, no mouthwash"
 5 = "blood and mouthwash, no urine"
 6 = "mouthwash and urine, no blood"
 7 = "all blood, urine and mouthwash";
data eight;
set tmp;
if  BioFin_BaseBloodCol_v1r0=BioFin_baseUrineCol_v1r0=BioFin_BaseMouthCol_v1r0=104430631 then BioCollections_v1r0=0;
if BioFin_BaseBloodCol_v1r0=353358909 and BioFin_baseUrineCol_v1r0=104430631 and BioFin_BaseMouthCol_v1r0= 104430631 then BioCollections_v1r0=1;
if BioFin_BaseBloodCol_v1r0=104430631 and BioFin_baseUrineCol_v1r0=353358909 and BioFin_BaseMouthCol_v1r0= 104430631 then BioCollections_v1r0=2;
if BioFin_BaseBloodCol_v1r0= 104430631 and BioFin_baseUrineCol_v1r0= 104430631 and BioFin_BaseMouthCol_v1r0=353358909 then BioCollections_v1r0=3;
if BioFin_BaseBloodCol_v1r0=353358909 and BioFin_baseUrineCol_v1r0=353358909 and BioFin_BaseMouthCol_v1r0= 104430631 then BioCollections_v1r0=4;
if BioFin_BaseBloodCol_v1r0=353358909 and BioFin_baseUrineCol_v1r0= 104430631 and BioFin_BaseMouthCol_v1r0=353358909  then BioCollections_v1r0=5;
if BioFin_BaseBloodCol_v1r0= 104430631 and BioFin_baseUrineCol_v1r0=353358909 and BioFin_BaseMouthCol_v1r0=353358909  then BioCollections_v1r0=6;
if BioFin_BaseBloodCol_v1r0=BioFin_baseUrineCol_v1r0=BioFin_BaseMouthCol_v1r0= 353358909 then BioCollections_v1r0=7;
format BioCollections_v1r0 typeyesnofmt.;
run;


PROC TEMPLATE;
   DEFINE STATGRAPH pie;
      BEGINGRAPH;
         LAYOUT REGION;
            PIECHART CATEGORY = BioCollections_v1r0 /
  		    OTHERSLICE=FALSE
            DATALABELLOCATION = INSIDE
            DATALABELCONTENT = ALL
			CATEGORYDIRECTION = CLOCKWISE
			DATASKIN = SHEEN
            START = 180 NAME = 'pie';
			/*FORMAT BioCollections_v1r0 typeyesnofmt.;*/
            DISCRETELEGEND 'pie' /
            TITLE = 'Percent (and number) of verified participants baseline collections by biospecimen type';
         ENDLAYOUT;
      ENDGRAPH;
   END;
RUN;

PROC SGRENDER DATA = eight
            TEMPLATE = pie;
FORMAT BioCollections_v1r0 typeyesnofmt.;
where connect_id=connectbio_id;
/*title "Percent (and number) of verified participants baseline collections by biospecimen type";*/
RUN;
/*proc freq data=eight; table BioCollections_v1r0/list;where connect_id=connectbio_id;run;*/

/*proc freq data=tmp;
title "Percent (and number) of verified participants Blood, Urine and Mouthwash complete collection among baseline biospeciment collections 04042022";
tables  BioBld_Complete*BioFin_baseUrineCol_v1r0*BioFin_BaseMouthCol_v1r0/list missing;
where connect_id=connectbio_id;
run;*UrineTube1_TubeCollected_yes*MWTube1_TubeCollected_yes*/
/*title "Table 11. Frequency of Blood collected by setting of all sites 04072022"; proc print data=Blood1 label; var Label Blood_Val2; 
run;
title "Table 12. Frequency of Urine collected by setting of all sites 04072022"; proc print data=Urine1 label;var Label Urine_Val2; run;
title "Table 13.A Frequency of MouthWash collected by setting all sites 04072022"; proc print data=mouth1 Label; var Label Mouth_Val2;run;
*/

proc sort data=blood1; by label; run;
proc sort data=urine1; by label; run;
proc sort data=mouth1; by label; run;

data biospe_two;merge blood1 (in=a) urine1;
by label;run;

data biospe_all;merge biospe_two (in=a) mouth1;
by label;run;

data biospe_all;set biospe_all;
Label Blood_Val2="Blood collected"
  Urine_Val2="Urine collected"
	Mouth_Val2="Mouthwash collected";
run;
/*Table 7*/
proc print data=Biospe_all Label noobs; 
title "Table 7. Number of blood, urine, and mouthwash collected by collection setting";
var Label Blood_Val2 Urine_Val2 Mouth_Val2;
run;

***the blood collection with baseline check in;
 data bloodcollect;set tmp2;
where BL_BioChk_Complete_v1r0^=. and BioSpm_Visit_v1r0=266600170;
run;

proc freq data=tmp2;
table BioSpm_Setting_v1r0*BioSpm_Visit_v1r0*BioFin_BaseBloodCol_v1r0 /out=FreqCount cumcol TOTPCT OUTPCT list noprint;
where BL_BioChk_Complete_v1r0^=. and BioSpm_Visit_v1r0=266600170;
format BioFin_BaseBloodCol_v1r0 BioColTubeCollFmt.;
run;

proc sort data=freqcount; by BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 BioFin_BaseBloodCol_v1r0;run;
/*data freqcount_w;length N_percent $16.; set freqcount;
by BioSpm_Visit_v1r0;
total=count*100/percent; 
N_percent=put(count, 4.2)||" ("||put(percent,4.2)||")";
if first.BioSpm_Visit_v1r0=1 and BioFin_BaseBloodCol_v1r0 =104430631 then do;
BioFin_BaseBloodCol_v1r0_Yes=lag(N_percent); BioFin_BaseBloodCol_v1r0_No=N_percent;
if last.BioSpm_Visit_v1r0=1 then output;end;
if first.BioSpm_Visit_v1r0=1 and BioFin_BaseBloodCol_v1r0 ^=104430631 then do;
BioFin_BaseBloodCol_v1r0_Yes=N_percent; BioFin_BaseBloodCol_v1r0_No="0(0)";
if last.BioSpm_Visit_v1r0=1 then output;end;
label total="Total Number of Check-in";
run;*/
data freqcount_w;length N_percent $16.; set freqcount;
by BioSpm_Setting_v1r0 BioSpm_Visit_v1r0;
total=count*100/percent; 
N_percent=put(count, 4.2)||" ("||put(percent,4.2)||")";
if first.BioSpm_Visit_v1r0=1 and BioFin_BaseBloodCol_v1r0 =104430631 then do;
BioFin_BaseBloodCol_v1r0_Yes=put((total-count), 6.0)||" ("||put(round((PCT_col-percent),0.01),4.2)||")";
BioFin_BaseBloodCol_v1r0_No=N_percent;output; end;
label BioFin_BaseBloodCol_v1r0_Yes="Collected"
 BioFin_BaseBloodCol_v1r0_No="Not Collected";run;

/*Table 8.*/ 
proc print data=freqcount_w noobs split='_' noobs label;
title "Table 8. Total number (and percent) of checked-in baseline blood collections";
var BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 BioFin_BaseBloodCol_v1r0_Yes BioFin_BaseBloodCol_v1r0_No total;
run;


data checkin;set eight;
if BioCollections_v1r0=0 then Bio_BLBUM_collected_v1r0=104430631;
else Bio_BLBUM_collected_v1r0=353358909;
where BL_BioChk_Complete_v1r0^=. and BioSpm_Visit_v1r0=266600170;
attrib Bio_BLBUM_collected_v1r0 format=BioColTubeCollFmt. 
label="any blood, urine or MW samples of any type collected at baseline check-in"; 
run;/*n=134*/
proc sort data=checkin; by BL_BioChk_Complete_v1r0;run;

proc freq data=checkin;
table BioSpm_Setting_v1r0*BioSpm_Visit_v1r0*Bio_BLBUM_collected_v1r0 /missing cumcol list noprint out=bumincomple;
where BL_BioChk_Complete_v1r0^=. and BioSpm_Visit_v1r0=266600170;
format Bio_BLBUM_collected_v1r0 BioColTubeCollFmt.;
run;
proc sort data=bumincomple; by Bio_BLBUM_collected_v1r0 BioSpm_Setting_v1r0 BioSpm_Visit_v1r0;run;/*n=3*/
data bumincomple_w;length N_percent $16.; set bumincomple; 
by BioSpm_Setting_v1r0 BioSpm_Visit_v1r0;
total=count*100/percent; 
N_percent=put(count, 4.2)||" ("||put(percent,4.2)||"%)";
Bio_BLBUM_collected_v1r0_char=lag(N_percent);
length Bio_BLBUM_collected_v1r0_Yes $16; length Bio_BLBUM_collected_v1r0_No $16.;
if first.BioSpm_Setting_v1r0=1 then do;
if first.BioSpm_Visit_v1r0=1 and last.BioSpm_Visit_v1r0=1 then do;
if Bio_BLBUM_collected_v1r0 =104430631 then do;
 Bio_BLBUM_collected_v1r0_No=N_percent;Bio_BLBUM_collected_v1r0_yes="0 (0%)";
end;
if Bio_BLBUM_collected_v1r0 ^=104430631 then do;
 Bio_BLBUM_collected_v1r0_Yes=N_percent;Bio_BLBUM_collected_v1r0_no="0 (0%)";
end;
end;
end;

 if first.BioSpm_Visit_v1r0=0 and last.BioSpm_Visit_v1r0=1 then do;
	Bio_BLBUM_collected_v1r0_yes=N_percent;
	Bio_BLBUM_collected_v1r0_no=Bio_BLBUM_collected_v1r0_char; end;
if last.BioSpm_Visit_v1r0=1 then output;
label total="Total Number of Baseline Check-in"
Bio_BLBUM_collected_v1r0_Yes="any sample collected"
Bio_BLBUM_collected_v1r0_No="No sample collected";
run;
/*Table 9. */
proc print data=bumincomple_w label noobs split='/' ;
title "Table 9. Total number (and percent) of checked-in baseline samples collections";
var BioSpm_Setting_v1r0 BioSpm_Visit_v1r0 Bio_BLBUM_collected_v1r0_Yes Bio_BLBUM_collected_v1r0_No total;
/*where Bio_BLBUM_collected_v1r0=104430631;*/
run;

/*Deviation*/
/*Jun. 30, as the biospecimen team comments, the table 11 will be deleted
proc freq data=deviation_long data=formatted;
table BioTube_type_v1r0*BioCol_TubeDeviation_v1r0
/noprint out=tmp_freq1 cumcol TOTPCT OUTPCT  list missing ;where BioCol_TubeID_v1r0^=" ";run; 

data tmp_freq1; set tmp_freq1; total_N= 100*count/pct_row; N_percent=put(count, 4.0)||" ("||put(pct_row,4.2)||")";
run;
proc sort data=tmp_freq1;by BioCol_TubeDeviation_v1r0; run;
proc transpose data=tmp_freq1 out = tube_devia prefix=BioTube_type_v1r0_;
by BioCol_TubeDeviation_v1r0;
var N_percent;
id BioTube_type_v1r0;
idlabel BioTube_type_v1r0;
run;
data tube_devia1;set tube_devia; if BioCol_TubeDeviation_v1r0 =353358909 and substr(BioTube_type_v1r0_urine,1,1) ^= "(" 
then BioTube_type_v1r0_urine ="  0";
if BioCol_TubeDeviation_v1r0 =353358909 and substr(BioTube_type_v1r0_MouthWash,1,1) ^= "(" 
then BioTube_type_v1r0_MouthWash ="  0";run;
proc print data=tube_devia1 label noobs;
title "Table 11. Number (%) of Tubes with any Deviations of all Sites at 07012022";
var BioCol_TubeDeviation_v1r0 BioTube_type_v1r0_blood BioTube_type_v1r0_urine BioTube_type_v1r0_mouthwash;
where  BioCol_TubeDeviation_v1r0=353358909;
run;*/
/*Table 10. */
title "Table 10. Number (and percent) of tubes with any deviation by site"; 
/*%Table1Print_CTSPedia(DSname=Biodev1, Space=Y);*/
data table10;set Biodev1;
site=label;if label="Site" then delete;
 run;
proc report data=table10  split='/' nowd ;
columns  site GroupVal2 GroupVal1 Total;
define site/ "Site" width=36 left;
define  GroupVal2/"Any Deviation" left width=20;
define GroupVal1 /"No Deviation" center width=20; 
define Total/"Total" center width=10; 
run;

***Jun. 30, to add the out of the Total Tubes Collected per site. (see example layout below);
/*proc print data=biodev1 split='/' noobs label;
title "Table 11. Number of Tubes with any deviation by Site at 07182022";
var label GroupVal2  Total;
run; */

/*Table 11. */
proc report data=dev_notes  split='/' nowd ;
title "Table 11. Number of deviations by biospecimen type and by tube type";
columns bio_type _label_ count;
define bio_type/"Biospecimen Types" width=20 left;
define _label_ /"Biospecimen collection Deviation?" left width=95;
define count /"Counts of Biospecimen Deviations" center width=10; 
run;/*n=17*/
/*%Table1Print_CTSPedia(DSname=Biodev1, Space=Y); not in version 2 (V2) which will be sent to Michelle";

title "Table 16. No any Discarded Tubes by site at 06172022"; /*%Table1Print_CTSPedia(DSname=Biodiscard, Space=Y);
title "Table 17. Counts of any Reason Not Collected by Tube Types of all Site"; %Table1Print_CTSPedia(DSname=BioNotColl, Space=Y);
ods listing;
proc print data=BioNotColl heading=h split='=' noobs label width=min;
title "Table 17. Counts of any Reason Not Collected by Tube Types of all Site";
var label GroupVal1 GroupVal2  GroupVal3 GroupVal4 Total;
run; 
ods pdf file= "\\Mac\Home\Documents\CONNECT_projects\Biospecimen_Feb2022\Jing_projects\biospecQC_03082022\SASoutputs\biospecimen_table17.pdf" ;
*/
/*Table 12. */

proc print data=notcol_allsite noobs label;
title "Table 12. Number of tube types not collected by site";
var RcrtES_Site_v1r0 SST1
SST2 ACD EDTA Heparin Mouthwash Urine total_notcol;
format RcrtES_Site_v1r0 site1fmt.;run;


data BioNotColl_4; 
length  GroupVal4 $8. GroupVal5 $8. ;set BioNotColl4;
if trim(left(label)) not in ("Tube Type","site", " ") then do;
 GroupVal4="0";  GroupVal5="0";
end;
if label = "Tube Type" then delete;
run; 
/*Table 13.*/ 
proc report data=BioNotColl_4 split='/' nowd;
title "Table 13. Number (and percent) of reason not collected by tube type and by site";
columns label GroupVal1 GroupVal2  GroupVal4 GroupVal5 GroupVal3 Total;
define label /"Tube Type" width=35 left;
define GroupVal1 /"Short draw" center width= 20;
define GroupVal2 /"Participants Attempted" center width= 20;
define GroupVal4 /"Other" center width= 20;
define GroupVal5 /"Participants Refusal" center width= 20;
define GroupVal3 /"Missing" center width=20;
define Total /"Total Tubes Not Collected" center width=10;
run; 

/*proc freq data=tubeID_NotColl_NotColNotes;
title "Table 13. Tube Types of NotCollected by Specimen Setting and Locations at 07182022"; 
tables BioSpm_Setting_v1r0*BioSpm_Location_v1r0*BioTube_NotCol_Type/list missing;
where Tubetype1 =" " and NotCollection1>0;
run;*/
/*basline Biospecimen Survey*/
/*Table 14.*/ 
proc freq data=tmp3 ; 
table SrvBLM_ResSrvCompl_v1r0/list missing outcum out=srvcomplte noprint; 
run;

data srvcomplte; set srvcomplte;
label SrvBLM_ResSrvCompl_v1r0="Survey Status"
count="Frequency"
Percent="Percent"
cum_pct="Cumulative Percent"
cum_freq="Cumulative Frequency";
run;

proc print data=srvcomplte noobs label;
title "Table 14. Total number and percent of research biospecimen survey status";
run;
***biospecimen comments note:1.) Remove ?y day·in title and header
2.) Relabel ?heckvisit·to Time****
3.)Table 17 retitle to Table 17. Timing of biospecimen survey completion relative to time of research biospecimen collection 07182022 
Relabel ‘checkvisit’ to ‘Survey Completion Time’ -07192022 quested by Michelle;


proc freq data=tmp3; 
table SrvBLM_ResSrvCompl_v1r0*checkvisit/missing out=sv_visit list noprint;
label checkvisit ="Survey Completion Time"; run;
data sv_visit; set sv_visit;
total=132;
label total="Total participants with biospecimen collection"
	SrvBLM_ResSrvCompl_v1r0="Survey Status";
format checkvisit checkdayfmt.;
run;
/*Table 15.*/ 
proc print data=sv_visit noobs label;
title "Table 15. Number and percent of research biospecimen survey completion time by survey status";
run;

proc format;
 value outfmt
  0 ="no outlier"
  1 ="outlier"
  9 = "Missing (not checked out)";
data Biotube_col1;set Biotube_col1;
  if abs(time_biochk/60) > 24 then biochk_outlier=1;
else if 0< =abs(time_biochk/60) < = 24 then biochk_outlier=0;
 if time_biochk=. then biochk_outlier=9;
 attrib biochk_outlier label="biospecimen checking time outlier(>24hrs)?" format=outfmt.;
 run;

/*Table 16.*/ 
proc means data=Biotube_col1 n nmiss min mean median max std maxdec=2 noprint;

var time_biochk;
class biochk_outlier;
format biochk_outlier outfmt.;
output out=sumstat n= nmiss= min= mean= median= max= std=/autoname ;
run;

data sumstat;set sumstat;
label time_biochk_N="Total"
 time_biochk_Nmiss="Missed"
 time_biochk_Min="Minimum"
 time_biochk_mean="Mean"
 time_biochk_median="Median"
 time_biochk_Max="Maximum"
 time_biochk_stdDev="Std Dev"
 biochk_outlier="Outlier Present?";
 run;
proc print data=sumstat noobs label; 
title "Table 16. Research biospecimen collection visit length (in minutes)";
var biochk_outlier time_biochk_N time_biochk_Nmiss time_biochk_min time_biochk_mean time_biochk_median time_biochk_max time_biochk_stddev;
where _type_=1; run;
ods graphics on;
proc sgplot data=Biotube_col1;
vbox time_biochk;
yaxis LABEL="Visit length (minutes)";
refline 1440 / lineattrs=(pattern=dot) label="24 hours";run;
/*Table 17. */
proc means data=Biotube_col1 n nmiss min mean median max std maxdec=2 noprint;
title "Research biospecimen collection visit length by site (in minutes)";
var time_biochk ;
class biochk_outlier RcrtES_Site_v1r0;
output out=sumstat_site n= nmiss= min= mean= median= max= std=/autoname ;
format biochk_outlier outfmt.;
run;
data sumstat_site;set sumstat_site;
label time_biochk_N="Total"
 time_biochk_Nmiss="Missed"
 time_biochk_Min="Minimum"
 time_biochk_mean="Mean"
 time_biochk_median="Median"
 time_biochk_Max="Maximum"
 time_biochk_stdDev="Std Dev"
 biochk_outlier="Outlier Present?";
 run;

proc print data=sumstat_site noobs label; 
title "Table 17. Research biospecimen collection visit length by site (in minutes)";
var biochk_outlier RcrtES_Site_v1r0 time_biochk_N time_biochk_Nmiss time_biochk_min time_biochk_mean time_biochk_median time_biochk_max time_biochk_stddev;
where _type_=3; run;
proc sgplot data=Biotube_col1;
vbox time_biochk/category=RcrtES_Site_v1r0;
yaxis LABEL="Visit length (minutes)";
refline 1440 / lineattrs=(pattern=dot) label="24 hours";run;

proc sgplot data=vis_site;
title "Number of biospecimen collection visits over time by site";
series x=wk_date y=visit / group=RcrtES_Site_v1r0 markers lineattrs=(pattern=solid)
                 break GROUPMC=RcrtES_Site_v1r0 groupms=RcrtES_Site_v1r0;
yaxis values=(0 to 16 by 1);
xaxis INTERVAL=week;
format wk_date datetime21. RcrtES_Site_v1r0 SiteFmt. ;
run;
ods graphics off;
ods pdf close;
***requested from Nicole on Jun. 27, 2022 for the biospecimen invitation;
proc sort data=biosbase_tube; by BioCol_ColTime_v1r0; run;
data biosbase_tube1; set biosbase_tube;
by BioSpm_Visit_v1r0;
if first.BioSpm_Visit_v1r0 then BioCol_Starttime=BioCol_ColTime_v1r0 ;
format BioCol_starttime datetime21.;
retain BioCol_Starttime;
 run;
data biosbase_tube1;
set biosbase_tube1;
wk=1+floor(intck("second",BioCol_Starttime,BioCol_ColTime_v1r0)/(60*60*24*7));
wk_date=BioCol_Starttime+7*60*60*24*(wk-1);
attrib wk_date label="date" format=datetime21.;
format BioCol_Starttime datetime21.;
run;

data time;
set biosbase_tube1;
keep RcrtES_Site_v1r0 wk wk_date BioCol_Starttime BioCol_ColTime_v1r0 ; run;
proc sort data=time; by RcrtES_Site_v1r0 wk;run;

***to do the weekly plots of biospecimen collection by site;
proc freq data=biosbase_tube1;
table BioCol_Starttime*wk*wk_date*RcrtES_Site_v1r0/list missing out=vis_site;run;
data vis_site; set vis_site; visit=count;
label visit="Number of visits";attrib wk_date label="date" format=datetime21.;
run;
proc sort data=vis_site; by RcrtES_Site_v1r0;run;
proc template;
define statgraph timeseries_plot_template;
begingraph;
	layout overlay;
		seriesplot x=wk_date y=visit /
			name="timeseries_plot"
			group=RcrtES_Site_v1r0;
	endlayout;
endgraph;
end;
run;

proc sgrender data=vis_site  
	template=timeseries_plot_template;
run;

data data.Biotube_col1_07182022;set Biotube_col1;run;

proc print data=recru_biospec_prod; var 
